### ISSUE TITLE
Tables changing height when clicking next arrow

### ISSUE THREAD

**Issue by dodgees** [opennebraska/landlord#19]
When I click the next arrow on some of the tables, the table size changes, forcing me to move the mouse to go to the next page.
It would be a better experience if the tables remained the same size to facilitate easily clicking from page to page.

It looks like this is caused when a property address wraps to a second line.

**Comment by ed-snodgrass** [comment]
What's the plan here? min-height on each row? I can't imagine it would ever wrap to the ~second~ third row.

**Comment by dodgees** [comment]
Seems like a fine approach to me. I didn't have anything in mind though.

**Comment by dodgees** [comment]
With content wrapping once, the row height jumps from 53 to 73. I set the row height to 75. ~fin~
