### ISSUE TITLE
Add about page

### ISSUE THREAD

**Issue by dodgees** [opennebraska/landlord#22]
Some page describing the project

**Comment by jhannah-mm** [comment]
Hopefully @elviejito can write up the verbiage. (e.g. http://nebraska.tif.report/about.html)
Let's include a link to github Issues (here) for reporting problems. :)

**Comment by jhannah** [comment]
@elviejito put this draft in Slack:
    How to use this website:
    There are three options for what you see on this website.  By clicking on the three little bars in the upper left hand corner, you can choose to view Omaha properties that are owned by people or companies located outside of Omaha (Out of Omaha), Omaha properties that are owned by people or companies located outside of Nebraska (Out of State), or Douglas County properties that are in Poor to Worn Out condition irrespective of the owner's location (Low Condition) .
    If, while you are in the Low Condition spreadsheet, for instance, you want to view only owners located in Omaha, simply click on Owner City and then enter "omaha" in the Search box by the upper right hand corner.
    Any column can be sorted up or down.  So you can sort by Owner Name or Owner Address or Owner City, etc.  You can even do this after you have created a view of, say - Owner City as Omaha – as in the previous paragraph.
    "Property Quality" refers to the durability of the building when it was constructed.  "Property Condition" means just what you would expect.
    When sorting by "STATE" (owner state of residence), the abbreviation "AE" stands for U.S. Armed Forces – Europe.
    All the data in this interactive database comes from publicly available sources – primarily the Douglas County Parcels database - https://data-dogis.opendata.arcgis.com/datasets/parcels

**Comment by dodgees** [comment]
Added
