### ISSUE TITLE
"Out of Omaha" incorrectly listing "REVERS HOMES INC" in BENNINGTON?

### ISSUE THREAD

**Issue by jhannah-mm** [opennebraska/landlord#24]
In Slack I believe @elviejito was reporting that the "Out of Omaha" report is listing "15416 S 2 ST, BENNINGTON" when it should not? [The third business rule](https://github.com/opennebraska/landlord/blob/master/src/parcel-parser.js#L25-L30) should be failing, omitting this entry, but is somehow listing it anyway?

**Comment by dodgees** [comment]
I looked for this and can't find it. Can you include a screenshot of what you two are seeing? Here's what I see: 
![image](https://user-images.githubusercontent.com/7633012/93228364-00fe0500-f73b-11ea-9064-e4b70c148e53.png)

**Comment by jhannah-mm** [comment]
@dodgees I reloaded the page and what I was seeing yesterday isn't there today, so I guess this is fixed. :)
