### ISSUE TITLE
Reload of https://opennebraska.github.io/landlord/out-of-omaha is 404

### ISSUE THREAD

**Issue by jhannah-mm** [opennebraska/landlord#26]
Clicking on "Out of Omaha" sends me to https://opennebraska.github.io/landlord/out-of-omaha which loads fine. Then I hit Reload and it's 404. This seems bad, since if we're going to have URLs for each report people will copy and paste those URLs into other websites / emails / whatever, and people who click them will get 404?
Chrome Version 85.0.4183.102 (current)
MacOS 10.15.6 (current)

**Comment by dodgees** [comment]
Trying solution referenced in create react app docs, https://github.com/rafgraph/spa-github-pages

**Comment by dodgees** [comment]
The above solution didn't work. I'll continue looking into it.

**Comment by dodgees** [comment]
Resolved on the second attempt with PR #29
