### ISSUE TITLE
Low Condition sort grouping by owner.

### ISSUE THREAD

**Issue by ed-snodgrass** [opennebraska/landlord#34]
Low Condition sort that would sort by number of properties, preferably with the landlords with the greatest number of properties first.  This would only catch the sloppiest landlords due to the fact that many of them set up multiple corporations - one for each property - which would mean more digging to create a thorough list.  But that goes beyond programming into deep research.  But it would still be interesting.

**Comment by ed-snodgrass** [comment]
I took a quick gander at the numbers, and there are 89 with more than one property, and 26 with more than 2 properties

**Comment by jhannah** [comment]
```
✗ cat lowPoorWornOutConditionParcels.json | jq | grep OWNER_NAME | sort | uniq -c | sort -nr | head
  10     "OWNER_NAME": "KOCH JOHN R",
   8     "OWNER_NAME": "OMAHA MUNICIPAL LAND BANK",
   7     "OWNER_NAME": "D&L REAL ESTATE GROUP LLC",
   6     "OWNER_NAME": "OMAHA ECONOMIC DEVELOPMENT",
   6     "OWNER_NAME": "AMP ENTERPRISES LLC",
   5     "OWNER_NAME": "SINCLAIR GROUP LLC",
   4     "OWNER_NAME": "SRE TAB BRANDEIS LLC",
...
```

**Comment by dodgees** [comment]
A put this together and threw it on the homepage, with similar tables for the other groupings (out of state, out of city)
