### ISSUE TITLE
Integrate eviction data?

### ISSUE THREAD

**Issue by jhannah-mm** [opennebraska/landlord#66]
In a meeting this evening Gary L Fischer said that his group has paid the state of Nebraska for all eviction data from 2011 - August 2020. It would be useful to integrate our property condition database w/ code violations (#52) w/ this eviction data?

**Comment by ed-snodgrass** [comment]
@jhannah  Did we get this data yet?

**Comment by jhannah-mm** [comment]
@eis95 not that I know of. A month ago Gary said it was available if we wanted it. @elviejito might know more?

**Comment by dodgees** [comment]
There is an open issue for this in landlords-api. Hopefully, we could use the API to pull these data in.

**Comment by smith-danni02** [comment]
I have the data. What do I do with it?

**Comment by jhannah-mm** [comment]
Closing this as a dupe. See this issue instead: https://github.com/codefornebraska/landlords-api/issues/2
