### ISSUE TITLE
Integrate all "Open" violations

### ISSUE THREAD

**Issue by jhannah-mm** [opennebraska/landlord#73]
In #52 we implemented cross-linking to omahapermits.com. In Slack Danni Smith said "it would be really helpful for us housing advocates" to integrate *more* of this data:
* pull all "open" cases (`StatusCurrent` not `Case Closed` or `Closed` or `Closed No Violations`)
* calculate how many days the cases have been "open"
* cross-link to the details (this is what #52 does)

**Comment by dodgees** [comment]
Finally got the scraping working. I'll work on getting the violations into the UI tonight.

**Comment by dodgees** [comment]
Closing this now that violations are on the property detail page. We can open another issue if we want changes for that.
