### ISSUE TITLE
Starter Page for people that don't want a wall of data

### ISSUE THREAD

**Issue by liester** [opennebraska/landlord#85]
Currently, the landing page for the landlord application is a wall of data.  We think this may be overwhelming to users that aren't as familiar with the process.

With this in mind, we would like to create a more inviting landing page.  One that could ask the user a simple question like "What is your address?" or "What is your landlord's name?"

That landing page may also be a good place for our aggregated metrics like total violations or landlord with most properties of particular qualities.

**Comment by dodgees** [comment]
What do you think about making a separate app with this idea that is aimed at renters trying to look into a landlord? Could be a simple landing page similar to google search page that says enter address or landlord's name. The search would just pull back the property detail page or landlord page. Other pages could just be things like renters' rights and resources.

The aggregated data mentioned could still be added to the Landlords of Omaha page, which would be aimed more at people doing policy work.

**Comment by liester** [comment]
After discussing the pros and cons we _think_ it will be easier to maintain a single application.

**Comment by dodgees** [comment]
This idea has turned into the rental lookup app. Closing
