### ISSUE TITLE
Fix github action to not fail when no updates are found

### ISSUE THREAD

**Issue by dodgees** [opennebraska/landlord#88]
In its current form, the GitHub action fails when no data has changed since the previous scrape. This appears to happen because no changes are staged to commit when we go to make the new commit. Would be good to do some research and verify this is the real cause of the problem. If so, put in a change to allow the action to exit gracefully if no new data is scraped.

**Comment by ronaldewatts** [comment]
The API changed, the `CLASS` attribute was being asked for but was removed. I'm fixing that.

**Comment by ronaldewatts** [comment]
Resolved and checked in updated files.
