### ISSUE TITLE
Improve UI for violations on property detail page

### ISSUE THREAD

**Issue by dodgees** [opennebraska/landlord#90]
![image](https://user-images.githubusercontent.com/7633012/110010254-b4f04e00-7ce3-11eb-9c27-de5c3d1e1157.png)
Right now the property detail page could use some UI improvements. The `view case` links just stack on top of one another endlessly, and the violations are a ton of cards. 

Make the violation data more presentable. Might be nice to make it search/sort/filterable as well. Don't need to make everything perfect. Just want to take a step to make things better.

**Comment by ronaldewatts** [comment]
Converted all the cards to a table and incorporated the case links
