### ISSUE TITLE
Metadata is boring, add photo etc. for more exciting social sharing

### ISSUE THREAD

**Issue by jhannah** [opennebraska/landlord#94]
<img width="550" alt="Screen Shot 2021-03-07 at 10 16 15 AM" src="https://user-images.githubusercontent.com/62206/110246734-64206580-7f2e-11eb-8859-d68c64c5e860.png">

We can fix via the debugger: https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fcodefornebraska.github.io%2Flandlord%2F

**Comment by dodgees** [comment]
![Screen Shot 2021-03-07 at 10 53 02 PM](https://user-images.githubusercontent.com/7633012/110276059-ff99f080-7f97-11eb-969c-54a362a9972e.png)
Might be worth picking a better picture, but here we are.
